### ISSUE TITLE
node-gyp rebuild error on windows

### ISSUE THREAD

**Issue by b3wii** [TooTallNate/node-lame#25]
```
c:\>npm install lame
npm http GET https://registry.npmjs.org/lame
npm http 304 https://registry.npmjs.org/lame
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/debuglog/0.0.2

> lame@1.0.3 install c:\node_modules\lame
> node-gyp rebuild


c:\node_modules\lame>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.23/node.lib
gyp http GET http://nodejs.org/dist/v0.10.23/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.23/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.23/x64/node.lib
Warning: Missing input files:
c:\node_modules\lame\build\deps\mpg123\..\..\..\deps\mpg123\test_output.c
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
MSBUILD : error MSB4062: Die Message-Aufgabe konnte nicht aus der Microsoft.Build.Tasks, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a-Assembly geladen werden. Die Datei oder Asse
mbly "Microsoft.Build.Tasks, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden. S
tellen Sie sicher, dass die <UsingTask>-Deklaration korrekt ist, die Assembly und alle zugehörigen Abhängigkeiten verfügbar sind und die Aufgabe eine öffentliche Klasse enthält, die Microsoft.Build.F
ramework.ITask implementiert. [c:\node_modules\lame\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\node_modules\lame
gyp ERR! node -v v0.10.23
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! lame@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.0.3 install script.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "lame"
npm ERR! cwd c:\
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\npm-debug.log
npm ERR! not ok code 0

c:\>
```

**Comment by macrobatic** [comment]
any update on this? I'm using npm 2.9.1 and node v0.12.3.
Thx.
