### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by darmie** [TooTallNate/node-lame#36]
Hi @TooTallNate , i am trying to use lame with icecast to stream live audio using Edcast. I was unable to run my node server file "Stream.js" I was getting this error

``` javascript
root@Darmie:/var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream# node stream.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Could not locate the bindings file. Tried:
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/build/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/build/Debug/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/build/Release/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/out/Debug/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/Debug/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/out/Release/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/Release/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/build/default/bindings.node
 → /var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/compiled/0.6.12/linux/x64/bindings.node
    at bindings (/var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/var/www/vhosts/crimson/crimsonfm.com/httpdocs/stream/node_modules/lame/lib/decoder.js:7:15)
    at Module._compile (module.js:441:26)
```

**Comment by sebastianwolfmw** [comment]
Hey, I'm having the same issue here. What could be causing this?

**Comment by EMCP** [comment]
node `v6` requires arm `v7+` apparently, and my raspberry pi B+ is arm `v6`
