### ISSUE TITLE
Cannot compile with nw-gyp

### ISSUE THREAD

**Issue by yunfong** [TooTallNate/node-lame#37]
my project is based on the node-webkit platform, node-webkit compile  c/c++ Addon use  a fork of node-gyp(https://github.com/rogerwang/nw-gyp), when i build node-lame , the error is as follows:

```
..\src\bindings.cc(29): error C2248: “v8::HandleScope::HandleScope”: Cannot access protected member(declaration at “v8::HandleScope”) [D:\tools\node-webkit\record\node_module
```

s\lame\build\b
indings.vcxproj]
          C:\Users\liuyunfeng.nw-gyp\0.10.2\deps\v8\include\v8.h(845) : see “v8::HandleScope::HandleScope” declaration.
          C:\Users\liuyunfeng.nw-gyp\0.10.2\deps\v8\include\v8.h(829) : 参见“v8::HandleScope”的声明
d:\tools\node-webkit\record\node_modules\lame\src\node_pointer.h(23): error C2882: “Buffer”: 在表达式中非法使用命名空间标识符 [D:\tools\node-webkit\record\node_modu
les\lame\build\bi
ndings.vcxproj]
d:\tools\node-webkit\record\node_modules\lame\src\node_pointer.h(23): error C2882: “Buffer”: 在表达式中非法使用命名空间标识符 [D:\tools\node-webkit\record\node_modu
les\lame\build\bi
ndings.vcxproj]
d:\tools\node-webkit\record\node_modules\lame\src\node_pointer.h(23): fatal error C1903: 无法从以前的错误中恢复；正在停止编译 [D:\tools\node-webkit\record\node_module
s\lame\build\bind
ings.vcxproj]
d:\tools\node-webkit\record\node_modules\lame\src\node_pointer.h(23): fatal error C1903: 无法从以前的错误中恢复；正在停止编译 [D:\tools\node-webkit\record\node_module
s\lame\build\bind
ings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\liuyunfeng\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\liuyunfeng\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" "build"
gyp ERR! cwd D:\tools\node-webkit\record\node_modules\lame
gyp ERR! node -v v0.10.26
gyp ERR! nw-gyp -v v0.12.2
gyp ERR! not ok

**Comment by m3nt0r** [comment]
And Mac using Homebrew version of Node (:
    node -v v0.10.35
    nw-gyp -v v0.12.4

```
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  LIBTOOL-STATIC Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  LIBTOOL-STATIC Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
../src/bindings.cc:29:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/kjell/.nw-gyp/0.11.5/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
1 error generated.
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
```

**Comment by hems** [comment]
+2

**Comment by smithandweb** [comment]
Confirmed on Ubuntu 14.04
Node: 0.12
node-gyp: 1.0.2

**Comment by virginielgb** [comment]
I'll add up to this:

```
4 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  LIBTOOL-STATIC Release/libmp3lame.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libmp3lame.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/myProject/node_modules/lame
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```
```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "lame" "--quiet"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by YMIndustries** [comment]
I am also experiencing this issue

pi@raspberrypi:~ $ npm install lame

> lame@1.2.3 install /home/pi/node_modules/lame
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/lame/build'
deps/mpg123/test.target.mk:117: warning: overriding recipe for target 'Release/test'
deps/lame/test.target.mk:125: warning: ignoring old recipe for target 'Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c: In function ‘do_gain_analysis’:
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable ‘rov’ [-Wunused-variable]
     RpgResult_t *const rov = &gfc->ov_rpg;
                        ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable ‘rsv’ [-Wunused-variable]
     RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                                ^
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable ‘cfg’ [-Wunused-variable]
     SessionConfig_t const *const cfg = &gfc->cfg;
                                  ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
^[OS  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
../deps/lame/libmp3lame/quantize.c: In function ‘VBR_new_iteration_loop’:
../deps/lame/libmp3lame/quantize.c:1734:28: warning: variable ‘fullframebits’ set but not used [-Wunused-but-set-variable]
         int     mean_bits, fullframebits;
                            ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  AR(target) Release/obj.target/deps/lame/libmp3lame.a
  COPY Release/libmp3lame.a
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c: In function ‘handle_id3v2’:
../deps/mpg123/src/libmpg123/parse.c:1013:31: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug("no useful ID3v2");
                               ^
../deps/mpg123/src/libmpg123/parse.c: In function ‘skip_junk’:
../deps/mpg123/src/libmpg123/parse.c:1081:71: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug1("hopefully found one at %"OFF_P, (off_p)fr->rd->tell(fr));
                                                                       ^
../deps/mpg123/src/libmpg123/parse.c: In function ‘wetwork’:
../deps/mpg123/src/libmpg123/parse.c:1149:114: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
    if(VERBOSE3) debug3("resync try %li at %"OFF_P", got newhead 0x%08lx", try, (off_p)fr->rd->tell(fr),  newhead);
                                                                                                                  ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c: In function ‘INT123_frame_outbuffer’:
../deps/mpg123/src/libmpg123/frame.c:184:4: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t’ [-Wformat=]
    if(NOQUIET) error2("have external buffer of size %"SIZE_P", need %"SIZE_P, (size_p)fr->buffer.size, size);
    ^
../deps/mpg123/src/libmpg123/frame.c: In function ‘INT123_frame_buffers’:
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(2*2*0x110*sizeof(real) > buffssize)
                            ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
../deps/mpg123/src/libmpg123/id3.c: In function ‘INT123_parse_new_id3’:
../deps/mpg123/src/libmpg123/id3.c:576:3: warning: right-hand operand of comma expression has no effect [-Wunused-value]
   ,1 \
   ^
../deps/mpg123/src/libmpg123/id3.c:661:35: note: in expansion of macro ‘threebytes_to_long’
        if(fr->id3v2.version == 2) threebytes_to_long(tagdata+pos, framesize);
                                   ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c: In function ‘plain_read’:
../deps/mpg123/src/libmpg123/readers.c:60:70: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug2("read %li bytes of %li", (long)ret, (long)count);
                                                                      ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘bc_add’:
../deps/mpg123/src/libmpg123/readers.c:630:93: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(size >=4) debug4("first bytes: %02x %02x %02x %02x", data[0], data[1], data[2], data[3]);
                                                                                             ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘bc_forget’:
../deps/mpg123/src/libmpg123/readers.c:728:42: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug("forget with nothing there!");
                                          ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘INT123_feed_more’:
../deps/mpg123/src/libmpg123/readers.c:763:33: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug("feed_more");
                                 ^
../deps/mpg123/src/libmpg123/readers.c:772:82: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
   (unsigned long)fr->rdat.buffer.last->size, (unsigned long)fr->rdat.buffer.size);
                                                                                  ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘buffered_fullread’:
../deps/mpg123/src/libmpg123/readers.c:848:97: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
    if(VERBOSE3) debug1("buffered_fullread: buffering %li bytes from stream (if > 0)", (long)got);
                                                                                                 ^
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if(got < sizeof(readbuf)) /* That naturally catches got == 0, too. */
           ^
../deps/mpg123/src/libmpg123/readers.c:867:73: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug2("wanted %li, got %li", (long)count, (long)gotcount);
                                                                         ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
../deps/mpg123/src/libmpg123/libmpg123.c: In function ‘mpg123_plain_strerror’:
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char*))
                             ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c: In function ‘III_dequantize_sample’:
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:804:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:818:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:842:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:890:4: note: in expansion of macro ‘REFRESH_MASK’
    REFRESH_MASK;
    ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1021:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1036:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1059:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1088:4: note: in expansion of macro ‘REFRESH_MASK’
    REFRESH_MASK;
    ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_arm.o
  AR(target) Release/obj.target/deps/mpg123/libmpg123.a
  COPY Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  AR(target) Release/obj.target/deps/lame/liblamevectorroutines.a
  COPY Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
In file included from ../src/bindings.cc:19:0:
../../nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
bindings.target.mk:103: recipe for target 'Release/obj.target/bindings/src/bindings.o' failed
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
make: Leaving directory '/home/pi/node_modules/lame/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/lame
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "lame"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
