### ISSUE TITLE
Does not seem to work with node 0.12.0

### ISSUE THREAD

**Issue by adius** [TooTallNate/node-lame#43]
```
/Users/adrian/Sites/univert/node_modules/lame/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/adrian/Sites/univert/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/adrian/Sites/univert/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adrian/Sites/univert/node_modules/lame/lib/decoder.js:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adrian/Sites/univert/node_modules/lame/index.js:6:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adrian/Sites/univert/src/wav2mp3.js:2:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adrian/Sites/univert/src/index.js:16:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adrian/Sites/univert/test/index.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/adrian/Sites/univert/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/adrian/Sites/univert/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/Users/adrian/Sites/univert/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/Users/adrian/Sites/univert/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by LinusU** [comment]
That error is because your `node-lame` was built for another version of Node.js (0.10 maybe?). This affects all compiled modules, to fix it run `npm rebuild`.

Unfortunately, `node-lame` dosen't yet compile with Node.js 0.12 (or io.js for that matter) due to a newer version of v8 being used.

The only error seems to be `error: no matching member function for call to 'Set'` thought. It dosen't accept more than 2 parameters anymore. Shouldn't be too hard to fix.

**Comment by LinusU** [comment]
Seems like that problem is fixed on `master` by switching to `ForceSet`. However, I instead get another problem which I can't quite make sense of.

```text
../node_modules/nan/nan_new.h:209:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_lame.cc:263:18: note: in instantiation of function template specialization 'NanNew<v8::Integer, unsigned long>' requested here
  NanReturnValue(NanNew<Integer>(b));
                 ^
../node_modules/nan/nan.h:299:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../node_modules/nan/nan_new.h:109:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:110:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
```

**Comment by LinusU** [comment]
For some reason NanNew dosen't like the `Integer` and `size_t` combination anymore. Casting the `size_t` to `uint32_t` fixes the issue, but another one soon arises.

```text
../node_modules/nan/nan_new.h:209:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_mpg123.cc:273:13: note: in instantiation of function template specialization 'NanNew<v8::Integer, unsigned long>' requested here
  argv[1] = NanNew<Integer>(r->done);
            ^
../node_modules/nan/nan_new.h:109:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:110:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
```

**Comment by LinusU** [comment]
pq at #45
