### ISSUE TITLE
Errors installing on Raspberry Pi

### ISSUE THREAD

**Issue by nfriedly** [TooTallNate/node-lame#58]
Hey, It looks like other people have gotten this working, so maybe it's just a user error, but on a pi (1) with a clean install of Raspbian, I got a ton of errors when trying to compile this module. I tried with both io.js v3.3.0 and node.js v0.12.2:

Console output for v3.3.0: http://pastebin.com/UM3077vK
Console output for v0.12.2: http://pastebin.com/uGgNs8Tf
npm-debug.log: http://pastebin.com/QxG8Tj2p

**Comment by wpcarro** [comment]
Any luck solving this? I am getting a ton of errors myself. I hope there is a workaround...

**Comment by nfriedly** [comment]
No, in my case, I ended up just calling `arecord` and piping the results to an ogg/opus encoder (I didn't actually want mp3, the library I was trying to use just installed it by default). You could try something along those lines though - just use shell commands for the actual audio capture & encoding and keep it out of node until you have a final result.

**Comment by jameh** [comment]
I hit this issue too. 
npm-debug.log http://hastebin.com/adehitapih.log

```
$ npm install lame

> lame@1.2.3 install /home/alarm/doorbell/node_modules/lame
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.15-2-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alarm/doorbell/node_modules/lame
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
/home/alarm/doorbell
+-- fs@0.0.2
+-- spark@1.0.0
`-- speaker@0.2.6

npm WARN enoent ENOENT: no such file or directory, open '/home/alarm/doorbell/package.json'
npm WARN doorbell No description
npm WARN doorbell No repository field.
npm WARN doorbell No README data
npm WARN doorbell No license field.
npm ERR! Linux 4.1.15-2-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "lame"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alarm/doorbell/npm-debug.log
```

**Comment by TooTallNate** [comment]
Make sure your g++ is v4.8 or newer.
