### ISSUE TITLE
Installation problems with lame@1.2.3 & lame@1.2.2

### ISSUE THREAD

**Issue by chennairadio** [TooTallNate/node-lame#68]
Hi,
I'm quite a newbie to node.js. I'm trying to work with lame, but in vain. I'm not even able to install this package. I keep getting the following error in windows 10.

C:\Users\kaush\AppData\Roaming\npm\node_modules\lame>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\kaush\AppData\Roaming\npm\node_modules\lame\build\deps\mpg123\..\..\..\deps\mpg123\test_output.c
**gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?**
gyp ERR! stack     at findMsbuild (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:128:23)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:110:11
gyp ERR! stack     at F (c:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:63:16)
gyp ERR! stack     at E (c:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:16
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kaush\AppData\Roaming\npm\node_modules\lame
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "lame@1.2.2" "--msvs_version=2015"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!

I even tried installing VS2015 c++ build tools and vs 2015 as mentioned in the 
[https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules](url)

**What surprises me more, is that I'm able to get most of the following packages mentioned in the above microsoft link to install except lame**

bson
bufferutil
kerberos
node-sass
sqlite3
phantomjs
utf-8-validate

<img width="960" alt="issue" src="https://cloud.githubusercontent.com/assets/20134761/16359988/d6d427de-3b17-11e6-8c9f-d54bc3b2c69b.png">

I also downgraded to v4.4.4 from v4.4.6 as mentioned in one of the issues too.

Pls help me. I'm kinda stuck with this issue.

**Comment by chennairadio** [comment]
Sorry guys for having bothered you. Today i again re-installed vs2015 build tools and tried to install with cmd instead of conemu and everything went fine. And hence closing this issue.
