### ISSUE TITLE
Failed at the lame@1.2.4 install script 'node-gyp rebuild'. Osx sierra

### ISSUE THREAD

**Issue by damienromito** [TooTallNate/node-lame#70]
I'm on Sierra (OSX 10.12). Lame is supposed to work on it?

```
> lame@1.2.4 install /Users/damienromito/Desktop/node-lame
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-10-20 16:17:14.062 xcodebuild[76606:6017007] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-10-20 16:17:14.063 xcodebuild[76606:6017007] Failed to load plugin at: /Users/damienromito/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
deps/mpg123/test.target.mk:152: warning: overriding commands for target `Release/test'
deps/lame/test.target.mk:160: warning: ignoring old commands for target `Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
../deps/lame/libmp3lame/VbrTag.c:263:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[0], 8u, 0xffu);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:265:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 3u, 7);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:266:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, (cfg->samplerate_out < 16000) ? 0 : 1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:267:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, cfg->version);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:268:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 2u, 4 - 3);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:269:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, (!cfg->error_protection) ? 1 : 0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:271:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 4u, eov->bitrate_index);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:272:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 2u, cfg->samplerate_index);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:273:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 1u, 0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:274:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 1u, cfg->extension);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:276:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, cfg->mode);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:277:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, eov->mode_ext);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:278:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 1u, cfg->copyright);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:279:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 1u, cfg->original);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:280:5: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, cfg->emphasis);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro 'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:430:23: warning: comparison of array 'pTagData->toc' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (pTagData->toc != NULL) {
            ~~~~~~~~~~^~~    ~~~~
16 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable 'cfg' [-Wunused-variable]
    SessionConfig_t const *const cfg = &gfc->cfg;
                                 ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable 'rsv' [-Wunused-variable]
    RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                               ^
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable 'rov' [-Wunused-variable]
    RpgResult_t *const rov = &gfc->ov_rpg;
                       ^
3 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
../deps/lame/libmp3lame/lame.c:628:13: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (EQ(gfp->compression_ratio, 0))
            ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:628:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:628:13: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (EQ(gfp->compression_ratio, 0))
            ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:628:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:1596:13: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (NEQ(RadioGain, GAIN_NOT_ENOUGH_SAMPLES)) {
            ^
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:1596:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:1596:13: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (NEQ(RadioGain, GAIN_NOT_ENOUGH_SAMPLES)) {
            ^
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:1596:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
4 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
../deps/lame/libmp3lame/presets.c:170:5: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp, set->quant_comp, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:170:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:171:5: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp_short, set->quant_comp_s, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:171:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:280:5: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp, abr_switch_map[r].quant_comp, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:280:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:281:5: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp_short, abr_switch_map[r].quant_comp_s, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:281:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
4 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  LIBTOOL-STATIC Release/libmp3lame.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libmp3lame.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/damienromito/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/damienromito/.nvm/versions/node/v6.0.0/bin/node" "/Users/damienromito/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/damienromito/Desktop/node-lame
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/damienromito/.nvm/versions/node/v6.0.0/bin/node" "/Users/damienromito/.nvm/versions/node/v6.0.0/bin/npm" "i"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/damienromito/Desktop/node-lame/npm-debug.log
```

**Comment by chsami** [comment]
Same problem, anybody got a fix?

**Comment by TooTallNate** [comment]
Pretty sure this happens when you have `libtool` installed from homebrew. You need the version from OS X Dev Tools.

**Comment by mikeal** [comment]
Same issue. I'm definitely using OS X Dev Tools libtool.

```
$ libtool  
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)`
```

**Comment by mikeal** [comment]
Actually, I may be getting a different error:

```
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
8 warnings generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_real.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  LIBTOOL-STATIC Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  LIBTOOL-STATIC Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
In file included from /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/include/stdint.h:9:0,
                 from /Users/mikeal/.node-gyp/6.3.1/include/node/v8.h:19,
                 from ../src/bindings.cc:17:
/usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/include-fixed/stdint.h:27:32: fatal error: sys/_types/_int8_t.h: No such file or directory
 #include <sys/_types/_int8_t.h>
                                ^
compilation terminated.
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
```

**Comment by mikeal** [comment]
Upgrading Node.js fixed it, sorry to bother :)
