### ISSUE TITLE
npm ERR! lame@1.2.4 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by pandavova** [TooTallNate/node-lame#71]
```
$ npm install lame
npm WARN package.json discorder@1.0.0 No repository field.

> lame@1.2.4 install C:\Users\Vova\discorder\node_modules\lame
> node-gyp rebuild


C:\Users\Vova\discorder\node_modules\lame>if not defined npm_config_node_gyp (node "C:\Users\Vova\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\Vova\discorder\node_modules\lame\build\deps\mpg123\..\..\..\deps\mpg123\test_output.c
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
C:\Users\Vova\discorder\node_modules\lame\build\deps\lame\mp3lame.vcxproj(20,3): error MSB4019: Das importierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datentr▒ger vorhanden ist.
C:\Users\Vova\discorder\node_modules\lame\build\deps\mpg123\mpg123.vcxproj(20,3): error MSB4019: Das importierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datentr▒ger vorhanden ist.
C:\Users\Vova\discorder\node_modules\lame\build\deps\lame\lamevectorroutines.vcxproj(20,3): error MSB4019: Das importierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datentr▒ger vorhanden ist.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Vova\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vova\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Vova\discorder\node_modules\lame
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vova\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "lame"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

```

How can i fix this? i dont get it,,,

**Comment by thewillwilson** [comment]
How did you fix it?

**Comment by pandavova** [comment]
I dont remember lol
