### ISSUE TITLE
build failing with node v12

### ISSUE THREAD

**Issue by cruzdanilo** [TooTallNate/node-lame#92]
module build is failing while using nodejs version > 12
build log:

```
> lame@1.2.4 install /Users/cruzdanilo/Documents/psicool/psicool-build-tool/node_modules/lame
> node-gyp rebuild

deps/mpg123/test.target.mk:177: warning: overriding commands for target `Release/test'
deps/lame/test.target.mk:185: warning: ignoring old commands for target `Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
../deps/lame/libmp3lame/VbrTag.c:263:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[0], 8u, 0xffu);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:265:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 3u, 7);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:266:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, (cfg->samplerate_out < 16000) ? 0 : 1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:267:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, cfg->version);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:268:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 2u, 4 - 3);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:269:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[1], 1u, (!cfg->error_protection) ? 1 : 0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:271:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 4u, eov->bitrate_index);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:272:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 2u, cfg->samplerate_index);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:273:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 1u, 0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:274:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[2], 1u, cfg->extension);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:276:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, cfg->mode);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:277:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, eov->mode_ext);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:278:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 1u, cfg->copyright);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:279:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 1u, cfg->original);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:280:5: warning: shifting a negative signed
      value is undefined [-Wshift-negative-value]
    SHIFT_IN_BITS_VALUE(buffer[3], 2u, cfg->emphasis);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/lame/libmp3lame/VbrTag.c:254:68: note: expanded from macro
      'SHIFT_IN_BITS_VALUE'
#define SHIFT_IN_BITS_VALUE(x,n,v) ( x = (x << (n)) | ( (v) & ~(-1 << (n)) ) )
                                                                ~~ ^
../deps/lame/libmp3lame/VbrTag.c:430:23: warning: comparison of array
      'pTagData->toc' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
        if (pTagData->toc != NULL) {
            ~~~~~~~~~~^~~    ~~~~
16 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable 'cfg'
      [-Wunused-variable]
    SessionConfig_t const *const cfg = &gfc->cfg;
                                 ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable 'rsv'
      [-Wunused-variable]
    RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                               ^
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable 'rov'
      [-Wunused-variable]
    RpgResult_t *const rov = &gfc->ov_rpg;
                       ^
3 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
../deps/lame/libmp3lame/lame.c:628:13: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (EQ(gfp->compression_ratio, 0))
            ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:628:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:628:13: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (EQ(gfp->compression_ratio, 0))
            ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:628:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:1596:13: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (NEQ(RadioGain, GAIN_NOT_ENOUGH_SAMPLES)) {
            ^
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:1596:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:168:12: note: expanded from macro 'EQ'
(fabs(a) > fabs(b)) \
           ^
../deps/lame/libmp3lame/lame.c:1596:13: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
        if (NEQ(RadioGain, GAIN_NOT_ENOUGH_SAMPLES)) {
            ^
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
../deps/lame/libmp3lame/lame.c:1596:13: note: use function 'abs' instead
../deps/lame/libmp3lame/machine.h:175:20: note: expanded from macro 'NEQ'
#define NEQ(a,b) (!EQ(a,b))
                   ^
../deps/lame/libmp3lame/machine.h:170:23: note: expanded from macro 'EQ'
 : (fabs((a)-(b)) <= (fabs(b) * 1e-6f)))
                      ^
4 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
../deps/lame/libmp3lame/presets.c:170:5: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp, set->quant_comp, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:170:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:171:5: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp_short, set->quant_comp_s, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:171:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:280:5: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp, abr_switch_map[r].quant_comp, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:280:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:281:5: warning: using floating point absolute
      value function 'fabs' when argument is of integer type [-Wabsolute-value]
    SET_OPTION(quant_comp_short, abr_switch_map[r].quant_comp_s, -1);
    ^
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
../deps/lame/libmp3lame/presets.c:281:5: note: use function 'abs' instead
../deps/lame/libmp3lame/presets.c:36:16: note: expanded from macro 'SET_OPTION'
    else if (!(fabs(lame_get_##opt(gfp) - def) > 0)) \
               ^
4 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  LIBTOOL-STATIC Release/libmp3lame.a
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c:184:27: warning: comparison of integers of
      different signs: 'off_t' (aka 'long long') and 'unsigned long'
      [-Wsign-compare]
  ...if(fr->track_frames > TRACK_MAX_FRAMES) fr->track_frames = 0; /* endles...
        ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison of integers of
      different signs: 'unsigned long' and 'int' [-Wsign-compare]
        if(2*2*0x110*sizeof(real) > buffssize)
           ~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison of integers
      of different signs: 'ssize_t' (aka 'long') and 'unsigned long'
      [-Wsign-compare]
                        if(got < sizeof(readbuf)) /* That naturally catc...
                           ~~~ ^ ~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison of
      integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char*))
                           ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c:804:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:818:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:842:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:890:4: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1021:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1036:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1059:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1088:4: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
8 warnings generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_real.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  LIBTOOL-STATIC Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  LIBTOOL-STATIC Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
../src/bindings.cc:26:6: error: variable has incomplete type 'void'
void InitLame(Handle<Object>);
     ^
../src/bindings.cc:26:15: error: use of undeclared identifier 'Handle'
void InitLame(Handle<Object>);
              ^
../src/bindings.cc:26:22: error: 'Object' does not refer to a value
void InitLame(Handle<Object>);
                     ^
/Users/cruzdanilo/.node-gyp/12.0.0/include/node/v8.h:3356:17: note: declared
      here
class V8_EXPORT Object : public Value {
                ^
../src/bindings.cc:26:29: error: expected expression
void InitLame(Handle<Object>);
                            ^
../src/bindings.cc:27:6: error: variable has incomplete type 'void'
void InitMPG123(Handle<Object>);
     ^
../src/bindings.cc:27:17: error: use of undeclared identifier 'Handle'
void InitMPG123(Handle<Object>);
                ^
../src/bindings.cc:27:24: error: 'Object' does not refer to a value
void InitMPG123(Handle<Object>);
                       ^
/Users/cruzdanilo/.node-gyp/12.0.0/include/node/v8.h:3356:17: note: declared
      here
class V8_EXPORT Object : public Value {
                ^
../src/bindings.cc:27:31: error: expected expression
void InitMPG123(Handle<Object>);
                              ^
../src/bindings.cc:29:6: error: variable has incomplete type 'void'
void Initialize(Handle<Object> target) {
     ^
../src/bindings.cc:29:17: error: use of undeclared identifier 'Handle'
void Initialize(Handle<Object> target) {
                ^
../src/bindings.cc:29:24: error: 'Object' does not refer to a value
void Initialize(Handle<Object> target) {
                       ^
/Users/cruzdanilo/.node-gyp/12.0.0/include/node/v8.h:3356:17: note: declared
      here
class V8_EXPORT Object : public Value {
                ^
../src/bindings.cc:29:32: error: use of undeclared identifier 'target'
void Initialize(Handle<Object> target) {
                               ^
../src/bindings.cc:29:39: error: expected ';' after top level declarator
void Initialize(Handle<Object> target) {
                                      ^
                                      ;
13 errors generated.
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cruzdanilo/.nodenv/versions/12.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/cruzdanilo/.nodenv/versions/12.0.0/bin/node" "/Users/cruzdanilo/.nodenv/versions/12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cruzdanilo/Documents/psicool/psicool-build-tool/node_modules/lame
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.4 install script.
```

**Comment by tom-23** [comment]
I'm having this issue too when running electron build. Hope this will get fixed soon.

**Comment by RocoGreen** [comment]
I have the same error but i downgraded my node 12 to 11.6.0 (last node 11 version) and it worked

**Comment by DmytroMysak** [comment]
Have the same issue, as workaround using node v10

**Comment by slikts** [comment]
node 10 can't be used in some contexts (like with NodeGui), so this is a fairly significant problem.

**Comment by suldashi** [comment]
I went ahead and spent an afternoon replacing the old Nan deprecated calls, now the package builds successfully for Node 12 without any warnings or errors. I made a PR, but until it's accepted, feel free to use this fork: https://github.com/suldashi/node-lame

**Comment by stheine** [comment]
I can confirm it works ok on node 12. Looking forward to get this published on npmjs.com.

**Comment by drom** [comment]
> I went ahead and spent an afternoon replacing the old Nan deprecated calls, now the package builds successfully for Node 12 without any warnings or errors. I made a PR, but until it's accepted, feel free to use this fork: https://github.com/suldashi/node-lame

Looking forward to seeing this change on NPM

**Comment by yjgaia** [comment]
When publish? ;(

**Comment by FelDev** [comment]
I think @TooTallNate  stopped maintaining this package. Last commit was in 2018 and it was the only one that year.

Maybe you should publish your fork as a new npm package @suldashi ?

**Comment by suldashi** [comment]
> I think @TooTallNate stopped maintaining this package. Last commit was in 2018 and it was the only one that year.
> 
> Maybe you should publish your fork as a new npm package @suldashi ?

It's not necessarily unmaintained just because it's rarely updated, maybe there's nothing to update? In any case, I was in touch with the original author a few weeks ago and he is aware of the issues and has promised to fix it. 

I just published this package on NPM and you can use it as usual. The name is `@suldashi/lame`. I hope the fixes are merged ASAP so I can deprecate it and the `lame` package can be used normally.

Install using `npm install -s @suldashi/lame` and import it using using `const lame = require("@suldashi/lame");`

**Comment by rphlmnbt** [comment]
> > I think @TooTallNate stopped maintaining this package. Last commit was in 2018 and it was the only one that year.
> > Maybe you should publish your fork as a new npm package @suldashi ?
> 
> It's not necessarily unmaintained just because it's rarely updated, maybe there's nothing to update? In any case, I was in touch with the original author a few weeks ago and he is aware of the issues and has promised to fix it.
> 
> I just published this package on NPM and you can use it as usual. The name is `@suldashi/lame`. I hope the fixes are merged ASAP so I can deprecate it and the `lame` package can be used normally.
> 
> Install using `npm install -s @suldashi/lame` and import it using using `const lame = require("@suldashi/lame");`

Thanks a lot for this! I've been trying to install lame for hours and wasn't able to. Yours worked flawlessly!
