### ISSUE TITLE
Install lame in electron

### ISSUE THREAD

**Issue by Edi-san** [TooTallNate/node-lame#94]
I have tried to download lame in my electron project. After some errors i got it installing but while using electron-rebuild, and the prebuild meantioned in the other issues i got this error:
`make: *** [bindings.target.mk:124: Release/obj.target/bindings/src/bindings.o] Error 1
make: Leaving directory '/home/edgarsilva/Projetos/yt-music-tray/node_modules/lame/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/edgarsilva/.nvm/versions/node/v8.16.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! stack     at emitTwo (events.js:126:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:214:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/edgarsilva/.nvm/versions/node/v8.16.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! build     at emitTwo (events.js:126:13)
prebuild ERR! build     at ChildProcess.emit (events.js:214:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

Tried node v12, v8.16.0, v11.6.0
But I get no errors running on normal nodejs has anyone tried lame on electron and got it working ?.

**Comment by lukaskral** [comment]
Having the same issue. I'm on Windows and use windows-build-tools package. 

When I run ```yarn --force``` the lame module is build correctly but with electron-rebuild I'm having the same error. In the end it says

```gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe`
failed with exit code: 1```
